{{- $fullname := include "flink-k8s-toolbox.fullname" . -}}
{{- $name := include "flink-k8s-toolbox.name" . -}}
{{- $chart := include "flink-k8s-toolbox.chart" . -}}
{{- $root := . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.name | default "flink-operator" | quote }}
  namespace: {{ $root.Values.namespace | default $root.Release.Namespace | quote }}
  labels:
    app: {{ $root.Values.name | default "flink-operator" | quote }}
    chart: {{ $chart }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $root.Values.controlPort | default 4444 }}
      targetPort: control
      protocol: TCP
      name: {{ $root.Values.controlPortName | default "control" }}
    - port: {{ $root.Values.monitorPort | default 8080 }}
      targetPort: monitor
      protocol: TCP
      name: {{ $root.Values.monitorPortName | default "monitor" }}
  selector:
    app: {{ $root.Values.name | default "flink-operator" | quote }}
