# Default values for flink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: nextbreakpoint/flink-k8s-toolbox
  tag: 1.1.3-beta
  pullPolicy: Always

replicas: 0

savepoint:
  interval: 600

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "250m"
